# -*- coding: utf-8 -*-
"""_ciudades.py — Tabla de ciudades populares (español) → zonas IANA.

Datos auxiliares para hora_mundial. Agregá acá ciudades nuevas.
"""
CIUDADES = {
    "buenos aires": "America/Argentina/Buenos_Aires",
    "tokio": "Asia/Tokyo",
    "tokyo": "Asia/Tokyo",
    "mexico": "America/Mexico_City",
    "mexico city": "America/Mexico_City",
    "ciudad de mexico": "America/Mexico_City",
    "monterrey": "America/Monterrey",
    "guadalajara": "America/Mexico_City",
    "madrid": "Europe/Madrid",
    "barcelona": "Europe/Madrid",
    "valencia": "Europe/Madrid",
    "sevilla": "Europe/Madrid",
    "londres": "Europe/London",
    "london": "Europe/London",
    "paris": "Europe/Paris",
    "parís": "Europe/Paris",
    "nueva york": "America/New_York",
    "new york": "America/New_York",
    "miami": "America/New_York",
    "boston": "America/New_York",
    "washington": "America/New_York",
    "chicago": "America/Chicago",
    "houston": "America/Chicago",
    "los angeles": "America/Los_Angeles",
    "los ángeles": "America/Los_Angeles",
    "san francisco": "America/Los_Angeles",
    "las vegas": "America/Los_Angeles",
    "seattle": "America/Los_Angeles",
    "denver": "America/Denver",
    "santiago": "America/Santiago",
    "santiago de chile": "America/Santiago",
    "bogota": "America/Bogota",
    "bogotá": "America/Bogota",
    "medellin": "America/Bogota",
    "lima": "America/Lima",
    "caracas": "America/Caracas",
    "quito": "America/Guayaquil",
    "la paz": "America/La_Paz",
    "asuncion": "America/Asuncion",
    "montevideo": "America/Montevideo",
    "rio de janeiro": "America/Sao_Paulo",
    "río de janeiro": "America/Sao_Paulo",
    "sao paulo": "America/Sao_Paulo",
    "brasilia": "America/Sao_Paulo",
    "sidney": "Australia/Sydney",
    "sídney": "Australia/Sydney",
    "sydney": "Australia/Sydney",
    "melbourne": "Australia/Melbourne",
    "berlin": "Europe/Berlin",
    "berlín": "Europe/Berlin",
    "roma": "Europe/Rome",
    "milan": "Europe/Rome",
    "milán": "Europe/Rome",
    "lisboa": "Europe/Lisbon",
    "amsterdam": "Europe/Amsterdam",
    "moscu": "Europe/Moscow",
    "moscú": "Europe/Moscow",
    "estambul": "Europe/Istanbul",
    "ateneas": "Europe/Athens",
    "atena": "Europe/Athens",
    "viena": "Europe/Vienna",
    "praga": "Europe/Prague",
    "dublin": "Europe/Dublin",
    "pekin": "Asia/Shanghai",
    "pekín": "Asia/Shanghai",
    "beijing": "Asia/Shanghai",
    "shanghai": "Asia/Shanghai",
    "shangai": "Asia/Shanghai",
    "hong kong": "Asia/Hong_Kong",
    "seul": "Asia/Seoul",
    "seúl": "Asia/Seoul",
    "dubai": "Asia/Dubai",
    "dubái": "Asia/Dubai",
    "singapur": "Asia/Singapore",
    "bangkok": "Asia/Bangkok",
    "yakarta": "Asia/Jakarta",
    "nueva delhi": "Asia/Kolkata",
    "mumbai": "Asia/Kolkata",
    "bombay": "Asia/Kolkata",
    "karachi": "Asia/Karachi",
    "el cairo": "Africa/Cairo",
    "cairo": "Africa/Cairo",
    "joburg": "Africa/Johannesburg",
    "johannesburgo": "Africa/Johannesburg",
    "ciudad del cabo": "Africa/Johannesburg",
    "cape town": "Africa/Johannesburg",
    "nairobi": "Africa/Nairobi",
    "tel aviv": "Asia/Jerusalem",
    "jerusalen": "Asia/Jerusalem",
    "jerusalén": "Asia/Jerusalem",
    "frankfurt": "Europe/Berlin",
    "vancouver": "America/Vancouver",
    "toronto": "America/Toronto",
    "montreal": "America/Toronto",
    "ciudad de guatemala": "America/Guatemala",
    "havanna": "America/Havana",
    "la habana": "America/Havana",
    "guayaquil": "America/Guayaquil",
    "san jose de costa rica": "America/Costa_Rica",
    "panamá": "America/Panama",
    "san juan": "America/Puerto_Rico",
    "aucaland": "Pacific/Auckland",
    "honolulu": "Pacific/Honolulu",
    "honolulo": "Pacific/Honolulu",
    "alaska": "America/Anchorage",
    "anchorage": "America/Anchorage",
    "canarias": "Atlantic/Canary",
    "las palmas": "Atlantic/Canary",
    "reikiavik": "Atlantic/Reykjavik",
}